@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Apr 19 21:32:28 +0200 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 5079212f401947e39664517b10906e44 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_states_1_behav xil_defaultlib.tb_states_1 -log elaborate.log"
call xelab  -wto 5079212f401947e39664517b10906e44 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_states_1_behav xil_defaultlib.tb_states_1 -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
